#ITEM INTERACT
#------------------------------------------------------
#----☆ Single Effects ☆----
#------------------------------------------------------
#--Item1
id1: 0
id1-msg: §aSpeed
#choose chat, popup, or tip
id1-msg-type: tip
#------Effect1
id1-eff1: 0
id1-eff1-dur: 0
id1-eff1-amp: 0
#------------------------------------------------------
#--Item2
id2: 0
id2-msg: §aHaste
#choose chat, popup, or tip
id2-msg-type: tip
#------Effect1
id2-eff1: 0
id2-eff1-dur: 0
id2-eff1-amp: 0
#------------------------------------------------------
#--Item3
id3: 0
id3-msg: §aStrength
#choose chat, popup, or tip
id3-msg-type: tip
#------Effect1
id3-eff1: 0
id3-eff1-dur: 0
id3-eff1-amp: 0
#------------------------------------------------------
#--Item4
id4: 0
id4-msg: §aJump Boost
#choose chat, popup, or tip
id4-msg-type: tip
#------Effect1
id4-eff1: 0
id4-eff1-dur: 0
id4-eff1-amp: 0
#------------------------------------------------------
#--Item5
id5: 0
id5-msg: §aRegeneration
#choose chat, popup, or tip
id5-msg-type: tip
#------Effect1
id5-eff1: 0
id5-eff1-dur: 0
id5-eff1-amp: 0
#------------------------------------------------------
#--Item6
id6: 351:8
id6-msg: §aResistance
#choose chat, popup, or tip
id6-msg-type: tip
#------Effect1
id6-eff1: 0
id6-eff1-dur: 0
id6-eff1-amp: 0
#------------------------------------------------------
#--Item7
id7: 0
id7-msg: §aFire Resistance
#choose chat, popup, or tip
id7-msg-type: tip
#------Effect1
id7-eff1: 0
id7-eff1-dur: 0
id7-eff1-amp: 0
#------------------------------------------------------
#--Item8
id8: 0
id8-msg: §aWater Breathing
#choose chat, popup, or tip
id8-msg-type: tip
#------Effect1
id8-eff1: 0
id8-eff1-dur: 0
id8-eff1-amp: 0
#------------------------------------------------------
#--Item9
id9: 0
id9-msg: §aInvincibility
#choose chat, popup, or tip
id9-msg-type: tip
#------Effect1
id9-eff1:  0
id9-eff1-dur: 0
id9-eff1-amp: 0
#------------------------------------------------------
#--Item10
id10: 351:12
id10-msg: §aNight Vision
#choose chat, popup, or tip
id10-msg-type: tip
#------Effect1
id10-eff1: 0
id10-eff1-dur: 0
id10-eff1-amp: 0
#------------------------------------------------------
#--Item11
id11: 351:13
id11-msg: §aHealth Boost
#choose chat, popup, or tip
id11-msg-type: tip
#------Effect1
id11-eff1: 0
id11-eff1-dur: 0
id11-eff1-amp: 0
#------------------------------------------------------
#--Item12
id12: 0
id12-msg: §aSaturation
#choose chat, popup, or tip
id12-msg-type: tip
#------Effect1
id12-eff1: 0
id12-eff1-dur: 0
id12-eff1-amp: 0
#------------------------------------------------------
#----☆ Triple Effects ☆----
#------------------------------------------------------
#--Item13
id13: 399
id13-msg: Tank v3
#choose chat, popup, or tip
id13-msg-type: chat
#------Effect1
id13-eff1: 11
id13-eff1-dur: 4000
id13-eff1-amp: 6
#------Effect2
id13-eff2: 21
id13-eff2-dur: 4000
id13-eff2-amp: 15
#------Effect3
id13-eff3: 10
id13-eff3-dur: 4000
id13-eff3-amp: 4
#------------------------------------------------------
#--Item14
id14: 370
id14-msg: Tank v2
#choose chat, popup, or tip
id14-msg-type: tip
#------Effect1
id13-eff1: 11
id13-eff1-dur: 4000
id13-eff1-amp: 5
#------Effect2
id13-eff2: 21
id13-eff2-dur: 4000
id13-eff2-amp: 10
#------Effect3
id13-eff3: 10
id13-eff3-dur: 4000
id13-eff3-amp: 3
#------------------------------------------------------
#--Item15
id15: 421
id15-msg: Tank v3
#choose chat, popup, or tip
id15-msg-type: tip
#------Effect1
id13-eff1: 11
id13-eff1-dur: 4000
id13-eff1-amp: 4
#------Effect2
id13-eff2: 21
id13-eff2-dur: 4000
id13-eff2-amp: 5
#------Effect3
id13-eff3: 10
id13-eff3-dur: 4000
id13-eff3-amp: 2
#------------------------------------------------------
#--Item16
id16: 0
id16-msg: §bExplorer 
#choose chat, popup, or tip
id16-msg-type: tip
#------Effect1
id16-eff1: 0
id16-eff1-dur: 0
id16-eff1-amp: 0
#------Effect2
id16-eff2: 0
id16-eff2-dur: 0
id16-eff2-amp: 0
#------Effect3
id16-eff3: 0
id16-eff3-dur: 0
id16-eff3-amp: 0
#------------------------------------------------------
#--Item17
id17: 0
id17-msg: §bTank
#choose chat, popup, or tip
id17-msg-type: tip
#------Effect1
id17-eff1: 0
id17-eff1-dur: 0
id17-eff1-amp: 0
#------Effect2
id17-eff2: 0
id17-eff2-dur: 0
id17-eff2-amp: 0
#------Effect3
id17-eff3: 0
id17-eff3-dur: 0
id17-eff3-amp: 0
#------------------------------------------------------

#BLOCK INTERACT
#------------------------------------------------------
#--Block1
block-id1: 0
block-id1-msg:
#choose chat, popup, or tip
block-id1-msg-type: popup
#------Effect1
block-id1-eff1: 0
block-id1-eff1-dur: 0
block-id1-eff1-amp: 0
#------Effect2
block-id1-eff2: 0
block-id1-eff2-dur: 0
block-id1-eff2-amp: 0
#------Effect3
block-id1-eff3: 0
block-id1-eff3-dur: 0
block-id1-eff3-amp: 0
#------------------------------------------------------
#--Block2
block-id2: 0
block-id2-msg:
#choose chat, popup, or tip
block-id2-msg-type: chat
#------Effect1
block-id2-eff1: 1
block-id2-eff1-dur: 20
block-id2-eff1-amp: 10
#------Effect2
block-id2-eff2: 2
block-id2-eff2-dur: 25
block-id2-eff2-amp: 15
#------Effect3
block-id2-eff3: 3
block-id2-eff3-dur: 25
block-id2-eff3-amp: 15
#------------------------------------------------------
#--Block3
block-id3: 0
block-id3-msg:
#choose chat, popup, or tip
block-id3-msg-type: tip
#------Effect1
block-id3-eff1: 1
block-id3-eff1-dur: 20
block-id3-eff1-amp: 10
#------Effect2
block-id3-eff2: 2
block-id3-eff2-dur: 25
block-id3-eff2-amp: 15
#------Effect3
block-id3-eff3: 3
block-id3-eff3-dur: 25
block-id3-eff3-amp: 15
#------------------------------------------------------
#--Block4
block-id4: 0
block-id4-msg:
#choose chat, popup, or tip
block-id4-msg-type: tip
#------Effect1
block-id4-eff1: 1
block-id4-eff1-dur: 20
block-id4-eff1-amp: 10
#------Effect2
block-id4-eff2: 2
block-id4-eff2-dur: 25
block-id4-eff2-amp: 15
#------Effect3
block-id4-eff3: 3
block-id4-eff3-dur: 25
block-id4-eff3-amp: 15
#------------------------------------------------------
#--Block5
block-id5: 0
block-id5-msg:
#choose chat, popup, or tip
block-id5-msg-type: popup
#------Effect1
block-id5-eff1: 1
block-id5-eff1-dur: 20
block-id5-eff1-amp: 10
#------Effect2
block-id5-eff2: 2
block-id5-eff2-dur: 25
block-id5-eff2-amp: 15
#------Effect3
block-id5-eff3: 3
block-id5-eff3-dur: 25
block-id5-eff3-amp: 15
#------------------------------------------------------
